version: '3.8'

services:
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin_container
    ports:
      - "8081:80"
    environment:
      PMA_HOST: mysql_container
      MYSQL_ROOT_PASSWORD: root
    networks:
      - shared_net

networks:
  shared_net:
    external: true
